services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=product_parser_db
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    volumes:
      - C:\postgres_datapart:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: product_parser_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/product_parser_db
      db-username: postgres
      db-password: admin
    depends_on:
      - db
    restart: always
